-- KAF Motors — seed: referans verisi + mevcut admin profili
-- 0001–0005 uygulandıktan SONRA çalıştır. Tamamen idempotent.
-- Marka verisi: github.com/filippofilip95/car-logos-dataset (387 marka, logo URL'li)
-- Model verisi: github.com/matthlavacka/car-list (889 model) — markalara slug ile bağlanır

-- Trigger'dan ONCE olusturulan admin kullanici(lar)i icin profiles kaydi
insert into profiles (id, ad_soyad)
select id, coalesce(raw_user_meta_data->>'ad_soyad', email)
from auth.users
on conflict (id) do nothing;

-- Markalar (car-logos-dataset)
insert into markalar (ad, slug, logo_url) values
  ('9ff','9ff','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/9ff.png'),
  ('Abadal','abadal','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/abadal.png'),
  ('Abarth','abarth','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/abarth.png'),
  ('Abbott-Detroit','abbott-detroit','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/abbott-detroit.png'),
  ('ABT','abt','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/abt.png'),
  ('AC','ac','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ac.png'),
  ('Acura','acura','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/acura.png'),
  ('Aiways','aiways','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/aiways.png'),
  ('Aixam','aixam','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/aixam.png'),
  ('Alfa Romeo','alfa-romeo','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/alfa-romeo.png'),
  ('Alpina','alpina','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/alpina.png'),
  ('Alpine','alpine','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/alpine.png'),
  ('Alta','alta','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/alta.png'),
  ('Alvis','alvis','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/alvis.png'),
  ('AMC','amc','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/amc.png'),
  ('Apollo','apollo','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/apollo.png'),
  ('Arash','arash','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/arash.png'),
  ('Arcfox','arcfox','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/arcfox.png'),
  ('Ariel','ariel','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ariel.png'),
  ('ARO','aro','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/aro.png'),
  ('Arrinera','arrinera','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/arrinera.png'),
  ('Arrival','arrival','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/arrival.png'),
  ('Artega','artega','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/artega.png'),
  ('Ascari','ascari','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ascari.png'),
  ('Askam','askam','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/askam.png'),
  ('Aspark','aspark','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/aspark.png'),
  ('Aston Martin','aston-martin','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/aston-martin.png'),
  ('Atalanta','atalanta','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/atalanta.png'),
  ('Auburn','auburn','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/auburn.png'),
  ('Audi','audi','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/audi.png'),
  ('Audi Sport','audi-sport','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/audi-sport.png'),
  ('Austin','austin','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/austin.png'),
  ('Autobacs','autobacs','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/autobacs.png'),
  ('Autobianchi','autobianchi','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/autobianchi.png'),
  ('Axon','axon','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/axon.png'),
  ('BAC','bac','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bac.png'),
  ('BAIC Motor','baic-motor','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/baic-motor.png'),
  ('Baojun','baojun','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/baojun.png'),
  ('BeiBen','beiben','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/beiben.png'),
  ('Bentley','bentley','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bentley.png'),
  ('Berkeley','berkeley','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/berkeley.png'),
  ('Berliet','berliet','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/berliet.png'),
  ('Bertone','bertone','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bertone.png'),
  ('Bestune','bestune','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bestune.png'),
  ('BharatBenz','bharatbenz','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bharatbenz.png'),
  ('Bitter','bitter','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bitter.png'),
  ('Bizzarrini','bizzarrini','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bizzarrini.png'),
  ('BMW','bmw','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bmw.png'),
  ('BMW M','bmw-m','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bmw-m.png'),
  ('Borgward','borgward','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/borgward.png'),
  ('Bowler','bowler','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bowler.png'),
  ('Brabus','brabus','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/brabus.png'),
  ('Brammo','brammo','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/brammo.png'),
  ('Brilliance','brilliance','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/brilliance.png'),
  ('Bristol','bristol','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bristol.png'),
  ('Brooke','brooke','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/brooke.png'),
  ('Bufori','bufori','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bufori.png'),
  ('Bugatti','bugatti','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/bugatti.png'),
  ('Buick','buick','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/buick.png'),
  ('BYD','byd','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/byd.png'),
  ('Byton','byton','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/byton.png'),
  ('Cadillac','cadillac','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/cadillac.png'),
  ('CAMC','camc','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/camc.png'),
  ('Canoo','canoo','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/canoo.png'),
  ('Caparo','caparo','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/caparo.png'),
  ('Carlsson','carlsson','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/carlsson.png'),
  ('Caterham','caterham','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/caterham.png'),
  ('Changan','changan','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/changan.png'),
  ('Changfeng','changfeng','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/changfeng.png'),
  ('Chery','chery','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/chery.png'),
  ('Chevrolet','chevrolet','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/chevrolet.png'),
  ('Chevrolet Corvette','chevrolet-corvette','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/chevrolet-corvette.png'),
  ('Chrysler','chrysler','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/chrysler.png'),
  ('Cisitalia','cisitalia','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/cisitalia.png'),
  ('Citroën','citroen','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/citroen.png'),
  ('Cizeta','cizeta','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/cizeta.png'),
  ('Cole','cole','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/cole.png'),
  ('Corre La Licorne','corre-la-licorne','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/corre-la-licorne.png'),
  ('Cupra','cupra','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/cupra.png'),
  ('Dacia','dacia','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/dacia.png'),
  ('Daewoo','daewoo','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/daewoo.png'),
  ('DAF','daf','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/daf.png'),
  ('Daihatsu','daihatsu','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/daihatsu.png'),
  ('Daimler','daimler','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/daimler.png'),
  ('Dartz','dartz','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/dartz.png'),
  ('Datsun','datsun','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/datsun.png'),
  ('David Brown','david-brown','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/david-brown.png'),
  ('Dayun','dayun','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/dayun.png'),
  ('De Tomaso','de-tomaso','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/de-tomaso.png'),
  ('Delage','delage','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/delage.png'),
  ('DeSoto','desoto','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/desoto.png'),
  ('Detroit Electric','detroit-electric','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/detroit-electric.png'),
  ('Devel Sixteen','devel-sixteen','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/devel-sixteen.png'),
  ('Diatto','diatto','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/diatto.png'),
  ('DINA','dina','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/dina.png'),
  ('DKW','dkw','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/dkw.png'),
  ('DMC','dmc','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/dmc.png'),
  ('Dodge','dodge','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/dodge.png'),
  ('Dodge Viper','dodge-viper','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/dodge-viper.png'),
  ('Dongfeng','dongfeng','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/dongfeng.png'),
  ('Donkervoort','donkervoort','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/donkervoort.png'),
  ('Drako','drako','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/drako.png'),
  ('DS','ds','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ds.png'),
  ('Duesenberg','duesenberg','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/duesenberg.png'),
  ('Eagle','eagle','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/eagle.png'),
  ('EDAG','edag','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/edag.png'),
  ('Edsel','edsel','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/edsel.png'),
  ('Eicher','eicher','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/eicher.png'),
  ('Elemental','elemental','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/elemental.png'),
  ('Elfin','elfin','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/elfin.png'),
  ('Elva','elva','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/elva.png'),
  ('Englon','englon','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/englon.png'),
  ('ERF','erf','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/erf.png'),
  ('Eterniti','eterniti','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/eterniti.png'),
  ('Exeed','exeed','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/exeed.png'),
  ('Facel Vega','facel-vega','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/facel-vega.png'),
  ('Faraday Future','faraday-future','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/faraday-future.png'),
  ('FAW','faw','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/faw.png'),
  ('FAW Jiefang','faw-jiefang','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/faw-jiefang.png'),
  ('Ferrari','ferrari','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ferrari.png'),
  ('Fiat','fiat','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/fiat.png'),
  ('Fioravanti','fioravanti','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/fioravanti.png'),
  ('Fisker','fisker','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/fisker.png'),
  ('Foden','foden','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/foden.png'),
  ('Force Motors','force-motors','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/force-motors.png'),
  ('Ford','ford','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ford.png'),
  ('Ford Mustang','ford-mustang','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ford-mustang.png'),
  ('Foton','foton','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/foton.png'),
  ('FPV','fpv','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/fpv.png'),
  ('Franklin','franklin','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/franklin.png'),
  ('Freightliner','freightliner','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/freightliner.png'),
  ('FSO','fso','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/fso.png'),
  ('GAC Group','gac-group','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/gac-group.png'),
  ('Gardner Douglas','gardner-douglas','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/gardner-douglas.png'),
  ('GAZ','gaz','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/gaz.png'),
  ('Geely','geely','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/geely.png'),
  ('General Motors','general-motors','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/general-motors.png'),
  ('Genesis','genesis','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/genesis.png'),
  ('Geo','geo','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/geo.png'),
  ('Geometry','geometry','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/geometry.png'),
  ('Gilbern','gilbern','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/gilbern.png'),
  ('Gillet','gillet','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/gillet.png'),
  ('Ginetta','ginetta','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ginetta.png'),
  ('GMC','gmc','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/gmc.png'),
  ('Golden Dragon','golden-dragon','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/golden-dragon.png'),
  ('Gonow','gonow','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/gonow.png'),
  ('Great Wall','great-wall','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/great-wall.png'),
  ('Grinnall','grinnall','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/grinnall.png'),
  ('Gumpert','gumpert','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/gumpert.png'),
  ('Hafei','hafei','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hafei.png'),
  ('Haima','haima','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/haima.png'),
  ('Haval','haval','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/haval.png'),
  ('Hawtai','hawtai','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hawtai.png'),
  ('Hennessey','hennessey','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hennessey.png'),
  ('Higer','higer','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/higer.png'),
  ('Hillman','hillman','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hillman.png'),
  ('Hindustan Motors','hindustan-motors','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hindustan-motors.png'),
  ('Hino','hino','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hino.png'),
  ('HiPhi','hiphi','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hiphi.png'),
  ('Hispano-Suiza','hispano-suiza','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hispano-suiza.png'),
  ('Holden','holden','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/holden.png'),
  ('Hommell','hommell','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hommell.png'),
  ('Honda','honda','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/honda.png'),
  ('Hongqi','hongqi','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hongqi.png'),
  ('Hongyan','hongyan','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hongyan.png'),
  ('Horch','horch','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/horch.png'),
  ('HSV','hsv','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hsv.png'),
  ('Hudson','hudson','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hudson.png'),
  ('Hummer','hummer','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hummer.png'),
  ('Hupmobile','hupmobile','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hupmobile.png'),
  ('Hyundai','hyundai','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/hyundai.png'),
  ('IC Bus','ic-bus','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ic-bus.png'),
  ('IH','ih','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ih.png'),
  ('IKCO','ikco','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ikco.png'),
  ('Infiniti','infiniti','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/infiniti.png'),
  ('Innocenti','innocenti','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/innocenti.png'),
  ('Intermeccanica','intermeccanica','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/intermeccanica.png'),
  ('International','international','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/international.png'),
  ('Irizar','irizar','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/irizar.png'),
  ('Isdera','isdera','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/isdera.png'),
  ('Iso','iso','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/iso.png'),
  ('Isuzu','isuzu','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/isuzu.png'),
  ('Iveco','iveco','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/iveco.png'),
  ('JAC','jac','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/jac.png'),
  ('Jaguar','jaguar','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/jaguar.png'),
  ('Jawa','jawa','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/jawa.png'),
  ('JBA Motors','jba-motors','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/jba-motors.png'),
  ('Jeep','jeep','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/jeep.png'),
  ('Jensen','jensen','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/jensen.png'),
  ('Jetour','jetour','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/jetour.png'),
  ('Jetta','jetta','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/jetta.png'),
  ('JMC','jmc','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/jmc.png'),
  ('Kaiser','kaiser','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/kaiser.png'),
  ('Kamaz','kamaz','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/kamaz.png'),
  ('Karlmann King','karlmann-king','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/karlmann-king.png'),
  ('Karma','karma','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/karma.png'),
  ('Keating','keating','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/keating.png'),
  ('Kenworth','kenworth','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/kenworth.png'),
  ('Kia','kia','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/kia.png'),
  ('King Long','king-long','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/king-long.png'),
  ('Koenigsegg','koenigsegg','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/koenigsegg.png'),
  ('KTM','ktm','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ktm.png'),
  ('Lada','lada','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lada.png'),
  ('Lagonda','lagonda','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lagonda.png'),
  ('Lamborghini','lamborghini','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lamborghini.png'),
  ('Lancia','lancia','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lancia.png'),
  ('Land Rover','land-rover','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/land-rover.png'),
  ('Landwind','landwind','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/landwind.png'),
  ('Laraki','laraki','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/laraki.png'),
  ('Leapmotor','leapmotor','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/leapmotor.png'),
  ('LEVC','levc','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/levc.png'),
  ('Lexus','lexus','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lexus.png'),
  ('Leyland','leyland','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/leyland.png'),
  ('Li Auto','li-auto','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/li-auto.png'),
  ('Lifan','lifan','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lifan.png'),
  ('Ligier','ligier','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ligier.png'),
  ('Lincoln','lincoln','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lincoln.png'),
  ('Lister','lister','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lister.png'),
  ('Lloyd','lloyd','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lloyd.png'),
  ('Lobini','lobini','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lobini.png'),
  ('Lordstown','lordstown','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lordstown.png'),
  ('Lotus','lotus','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lotus.png'),
  ('Lucid','lucid','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lucid.png'),
  ('Luxgen','luxgen','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/luxgen.png'),
  ('Lynk & Co','lynk-and-co','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/lynk-and-co.png'),
  ('Mack','mack','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mack.png'),
  ('Mahindra','mahindra','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mahindra.png'),
  ('MAN','man','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/man.png'),
  ('Mansory','mansory','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mansory.png'),
  ('Marcos','marcos','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/marcos.png'),
  ('Marlin','marlin','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/marlin.png'),
  ('Maserati','maserati','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/maserati.png'),
  ('Mastretta','mastretta','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mastretta.png'),
  ('Maxus','maxus','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/maxus.png'),
  ('Maybach','maybach','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/maybach.png'),
  ('MAZ','maz','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/maz.png'),
  ('Mazda','mazda','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mazda.png'),
  ('Mazzanti','mazzanti','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mazzanti.png'),
  ('McLaren','mclaren','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mclaren.png'),
  ('Melkus','melkus','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/melkus.png'),
  ('Mercedes-AMG','mercedes-amg','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mercedes-amg.png'),
  ('Mercedes-Benz','mercedes-benz','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mercedes-benz.png'),
  ('Mercury','mercury','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mercury.png'),
  ('Merkur','merkur','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/merkur.png'),
  ('MEV','mev','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mev.png'),
  ('MG','mg','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mg.png'),
  ('Microcar','microcar','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/microcar.png'),
  ('Mini','mini','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mini.png'),
  ('Mitsubishi','mitsubishi','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mitsubishi.png'),
  ('Mitsuoka','mitsuoka','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mitsuoka.png'),
  ('MK','mk','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mk.png'),
  ('Morgan','morgan','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/morgan.png'),
  ('Morris','morris','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/morris.png'),
  ('Mosler','mosler','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/mosler.png'),
  ('Navistar','navistar','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/navistar.png'),
  ('NEVS','nevs','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/nevs.png'),
  ('Nikola','nikola','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/nikola.png'),
  ('NIO','nio','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/nio.png'),
  ('Nissan','nissan','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/nissan.png'),
  ('Nissan GT-R','nissan-gt-r','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/nissan-gt-r.png'),
  ('Nissan Nismo','nissan-nismo','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/nissan-nismo.png'),
  ('Noble','noble','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/noble.png'),
  ('Oldsmobile','oldsmobile','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/oldsmobile.png'),
  ('Oltcit','oltcit','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/oltcit.png'),
  ('Omoda','omoda','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/omoda.png'),
  ('Opel','opel','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/opel.png'),
  ('OSCA','osca','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/osca.png'),
  ('Paccar','paccar','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/paccar.png'),
  ('Packard','packard','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/packard.png'),
  ('Pagani','pagani','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/pagani.png'),
  ('Panhard','panhard','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/panhard.png'),
  ('Panoz','panoz','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/panoz.png'),
  ('Pegaso','pegaso','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/pegaso.png'),
  ('Perodua','perodua','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/perodua.png'),
  ('Peterbilt','peterbilt','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/peterbilt.png'),
  ('Peugeot','peugeot','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/peugeot.png'),
  ('PGO','pgo','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/pgo.png'),
  ('Pierce-Arrow','pierce-arrow','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/pierce-arrow.png'),
  ('Pininfarina','pininfarina','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/pininfarina.png'),
  ('Plymouth','plymouth','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/plymouth.png'),
  ('Polestar','polestar','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/polestar.png'),
  ('Pontiac','pontiac','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/pontiac.png'),
  ('Porsche','porsche','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/porsche.png'),
  ('Praga','praga','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/praga.png'),
  ('Premier','premier','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/premier.png'),
  ('Prodrive','prodrive','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/prodrive.png'),
  ('Proton','proton','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/proton.png'),
  ('Qoros','qoros','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/qoros.png'),
  ('Radical','radical','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/radical.png'),
  ('RAM','ram','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ram.png'),
  ('Rambler','rambler','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/rambler.png'),
  ('Ranz','ranz','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ranz.png'),
  ('Renault','renault','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/renault.png'),
  ('Renault Samsung','renault-samsung','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/renault-samsung.png'),
  ('Rezvani','rezvani','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/rezvani.png'),
  ('Riley','riley','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/riley.png'),
  ('Rimac','rimac','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/rimac.png'),
  ('Rinspeed','rinspeed','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/rinspeed.png'),
  ('Rivian','rivian','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/rivian.png'),
  ('Roewe','roewe','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/roewe.png'),
  ('Rolls-Royce','rolls-royce','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/rolls-royce.png'),
  ('Ronart','ronart','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ronart.png'),
  ('Rossion','rossion','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/rossion.png'),
  ('Rover','rover','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/rover.png'),
  ('RUF','ruf','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ruf.png'),
  ('Saab','saab','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/saab.png'),
  ('SAIC Motor','saic-motor','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/saic-motor.png'),
  ('Saipa','saipa','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/saipa.png'),
  ('Saleen','saleen','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/saleen.png'),
  ('Saturn','saturn','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/saturn.png'),
  ('Scania','scania','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/scania.png'),
  ('Scion','scion','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/scion.png'),
  ('SEAT','seat','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/seat.png'),
  ('Setra','setra','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/setra.png'),
  ('SEV','sev','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/sev.png'),
  ('Shacman','shacman','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/shacman.png'),
  ('Simca','simca','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/simca.png'),
  ('Singer','singer','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/singer.png'),
  ('Singulato','singulato','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/singulato.png'),
  ('Sinotruk','sinotruk','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/sinotruk.png'),
  ('Sisu','sisu','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/sisu.png'),
  ('Škoda','skoda','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/skoda.png'),
  ('Smart','smart','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/smart.png'),
  ('Soueast','soueast','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/soueast.png'),
  ('Spania GTA','spania-gta','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/spania-gta.png'),
  ('Spirra','spirra','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/spirra.png'),
  ('Spyker','spyker','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/spyker.png'),
  ('SsangYong','ssangyong','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ssangyong.png'),
  ('SSC','ssc','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ssc.png'),
  ('Sterling','sterling','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/sterling.png'),
  ('Studebaker','studebaker','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/studebaker.png'),
  ('Stutz','stutz','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/stutz.png'),
  ('Subaru','subaru','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/subaru.png'),
  ('Suffolk','suffolk','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/suffolk.png'),
  ('Suzuki','suzuki','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/suzuki.png'),
  ('Talbot','talbot','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/talbot.png'),
  ('Tata','tata','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/tata.png'),
  ('Tatra','tatra','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/tatra.png'),
  ('Tauro','tauro','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/tauro.png'),
  ('TechArt','techart','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/techart.png'),
  ('Tesla','tesla','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/tesla.png'),
  ('Toyota','toyota','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/toyota.png'),
  ('Toyota Alphard','toyota-alphard','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/toyota-alphard.png'),
  ('Toyota Century','toyota-century','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/toyota-century.png'),
  ('Toyota Crown','toyota-crown','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/toyota-crown.png'),
  ('Tramontana','tramontana','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/tramontana.png'),
  ('Trion','trion','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/trion.png'),
  ('Triumph','triumph','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/triumph.png'),
  ('Troller','troller','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/troller.png'),
  ('Tucker','tucker','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/tucker.png'),
  ('TVR','tvr','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/tvr.png'),
  ('UAZ','uaz','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/uaz.png'),
  ('UD','ud','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ud.png'),
  ('Ultima','ultima','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/ultima.png'),
  ('Vandenbrink','vandenbrink','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/vandenbrink.png'),
  ('Vauxhall','vauxhall','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/vauxhall.png'),
  ('Vector','vector','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/vector.png'),
  ('Vencer','vencer','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/vencer.png'),
  ('Venturi','venturi','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/venturi.png'),
  ('Venucia','venucia','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/venucia.png'),
  ('VinFast','vinfast','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/vinfast.png'),
  ('VLF','vlf','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/vlf.png'),
  ('Volkswagen','volkswagen','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/volkswagen.png'),
  ('Volvo','volvo','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/volvo.png'),
  ('W Motors','w-motors','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/w-motors.png'),
  ('Wanderer','wanderer','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/wanderer.png'),
  ('Wartburg','wartburg','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/wartburg.png'),
  ('Weltmeister','weltmeister','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/weltmeister.png'),
  ('Western Star','western-star','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/western-star.png'),
  ('Westfield','westfield','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/westfield.png'),
  ('WEY','wey','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/wey.png'),
  ('Wiesmann','wiesmann','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/wiesmann.png'),
  ('Willys-Overland','willys-overland','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/willys-overland.png'),
  ('Workhorse','workhorse','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/workhorse.png'),
  ('Wuling','wuling','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/wuling.png'),
  ('XPeng','xpeng','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/xpeng.png'),
  ('Yulon','yulon','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/yulon.png'),
  ('Yutong','yutong','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/yutong.png'),
  ('Zarooq Motors','zarooq-motors','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/zarooq-motors.png'),
  ('Zastava','zastava','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/zastava.png'),
  ('ZAZ','zaz','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/zaz.png'),
  ('Zeekr','zeekr','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/zeekr.png'),
  ('Zenos','zenos','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/zenos.png'),
  ('Zenvo','zenvo','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/zenvo.png'),
  ('Zhongtong','zhongtong','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/zhongtong.png'),
  ('Zinoro','zinoro','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/zinoro.png'),
  ('Zotye','zotye','https://raw.githubusercontent.com/filippofilip95/car-logos-dataset/master/logos/optimized/zotye.png')
on conflict do nothing;

-- Modeller (car-list) — markalar.slug uzerinden eslenir (ad aksan farklarindan bagimsiz)
insert into modeller (marka_id, ad, slug)
select m.id, x.ad, x.slug
from markalar m
join (values
  ('seat','Alhambra','alhambra'),
  ('seat','Altea','altea'),
  ('seat','Altea XL','altea-xl'),
  ('seat','Arosa','arosa'),
  ('seat','Cordoba','cordoba'),
  ('seat','Cordoba Vario','cordoba-vario'),
  ('seat','Exeo','exeo'),
  ('seat','Ibiza','ibiza'),
  ('seat','Ibiza ST','ibiza-st'),
  ('seat','Exeo ST','exeo-st'),
  ('seat','Leon','leon'),
  ('seat','Leon ST','leon-st'),
  ('seat','Inca','inca'),
  ('seat','Mii','mii'),
  ('seat','Toledo','toledo'),
  ('renault','Captur','captur'),
  ('renault','Clio','clio'),
  ('renault','Clio Grandtour','clio-grandtour'),
  ('renault','Espace','espace'),
  ('renault','Express','express'),
  ('renault','Fluence','fluence'),
  ('renault','Grand Espace','grand-espace'),
  ('renault','Grand Modus','grand-modus'),
  ('renault','Grand Scenic','grand-scenic'),
  ('renault','Kadjar','kadjar'),
  ('renault','Kangoo','kangoo'),
  ('renault','Kangoo Express','kangoo-express'),
  ('renault','Koleos','koleos'),
  ('renault','Laguna','laguna'),
  ('renault','Laguna Grandtour','laguna-grandtour'),
  ('renault','Latitude','latitude'),
  ('renault','Mascott','mascott'),
  ('renault','Mégane','megane'),
  ('renault','Mégane CC','megane-cc'),
  ('renault','Mégane Combi','megane-combi'),
  ('renault','Mégane Grandtour','megane-grandtour'),
  ('renault','Mégane Coupé','megane-coupe'),
  ('renault','Mégane Scénic','megane-scenic'),
  ('renault','Scénic','scenic'),
  ('renault','Talisman','talisman'),
  ('renault','Talisman Grandtour','talisman-grandtour'),
  ('renault','Thalia','thalia'),
  ('renault','Twingo','twingo'),
  ('renault','Wind','wind'),
  ('renault','Zoé','zoe'),
  ('peugeot','1007','1007'),
  ('peugeot','107','107'),
  ('peugeot','106','106'),
  ('peugeot','108','108'),
  ('peugeot','2008','2008'),
  ('peugeot','205','205'),
  ('peugeot','205 Cabrio','205-cabrio'),
  ('peugeot','206','206'),
  ('peugeot','206 CC','206-cc'),
  ('peugeot','206 SW','206-sw'),
  ('peugeot','207','207'),
  ('peugeot','207 CC','207-cc'),
  ('peugeot','207 SW','207-sw'),
  ('peugeot','306','306'),
  ('peugeot','307','307'),
  ('peugeot','307 CC','307-cc'),
  ('peugeot','307 SW','307-sw'),
  ('peugeot','308','308'),
  ('peugeot','308 CC','308-cc'),
  ('peugeot','308 SW','308-sw'),
  ('peugeot','309','309'),
  ('peugeot','4007','4007'),
  ('peugeot','4008','4008'),
  ('peugeot','405','405'),
  ('peugeot','406','406'),
  ('peugeot','407','407'),
  ('peugeot','407 SW','407-sw'),
  ('peugeot','5008','5008'),
  ('peugeot','508','508'),
  ('peugeot','508 SW','508-sw'),
  ('peugeot','605','605'),
  ('peugeot','806','806'),
  ('peugeot','607','607'),
  ('peugeot','807','807'),
  ('peugeot','Bipper','bipper'),
  ('peugeot','RCZ','rcz'),
  ('dacia','Dokker','dokker'),
  ('dacia','Duster','duster'),
  ('dacia','Lodgy','lodgy'),
  ('dacia','Logan','logan'),
  ('dacia','Logan MCV','logan-mcv'),
  ('dacia','Logan Van','logan-van'),
  ('dacia','Sandero','sandero'),
  ('dacia','Solenza','solenza'),
  ('citroen','Berlingo','berlingo'),
  ('citroen','C-Crosser','c-crosser'),
  ('citroen','C-Elissée','c-elissee'),
  ('citroen','C-Zero','c-zero'),
  ('citroen','C1','c1'),
  ('citroen','C2','c2'),
  ('citroen','C3','c3'),
  ('citroen','C3 Picasso','c3-picasso'),
  ('citroen','C4','c4'),
  ('citroen','C4 Aircross','c4-aircross'),
  ('citroen','C4 Cactus','c4-cactus'),
  ('citroen','C4 Coupé','c4-coupe'),
  ('citroen','C4 Grand Picasso','c4-grand-picasso'),
  ('citroen','C4 Sedan','c4-sedan'),
  ('citroen','C5','c5'),
  ('citroen','C5 Break','c5-break'),
  ('citroen','C5 Tourer','c5-tourer'),
  ('citroen','C6','c6'),
  ('citroen','C8','c8'),
  ('citroen','DS3','ds3'),
  ('citroen','DS4','ds4'),
  ('citroen','DS5','ds5'),
  ('citroen','Evasion','evasion'),
  ('citroen','Jumper','jumper'),
  ('citroen','Jumpy','jumpy'),
  ('citroen','Saxo','saxo'),
  ('citroen','Nemo','nemo'),
  ('citroen','Xantia','xantia'),
  ('citroen','Xsara','xsara'),
  ('opel','Agila','agila'),
  ('opel','Ampera','ampera'),
  ('opel','Antara','antara'),
  ('opel','Astra','astra'),
  ('opel','Astra cabrio','astra-cabrio'),
  ('opel','Astra caravan','astra-caravan'),
  ('opel','Astra coupé','astra-coupe'),
  ('opel','Calibra','calibra'),
  ('opel','Campo','campo'),
  ('opel','Cascada','cascada'),
  ('opel','Corsa','corsa'),
  ('opel','Frontera','frontera'),
  ('opel','Insignia','insignia'),
  ('opel','Insignia kombi','insignia-kombi'),
  ('opel','Kadett','kadett'),
  ('opel','Meriva','meriva'),
  ('opel','Mokka','mokka'),
  ('opel','Movano','movano'),
  ('opel','Omega','omega'),
  ('opel','Signum','signum'),
  ('opel','Vectra','vectra'),
  ('opel','Vectra Caravan','vectra-caravan'),
  ('opel','Vivaro','vivaro'),
  ('opel','Vivaro Kombi','vivaro-kombi'),
  ('opel','Zafira','zafira'),
  ('alfa-romeo','145','145'),
  ('alfa-romeo','146','146'),
  ('alfa-romeo','147','147'),
  ('alfa-romeo','155','155'),
  ('alfa-romeo','156','156'),
  ('alfa-romeo','156 Sportwagon','156-sportwagon'),
  ('alfa-romeo','159','159'),
  ('alfa-romeo','159 Sportwagon','159-sportwagon'),
  ('alfa-romeo','164','164'),
  ('alfa-romeo','166','166'),
  ('alfa-romeo','4C','4c'),
  ('alfa-romeo','Brera','brera'),
  ('alfa-romeo','GTV','gtv'),
  ('alfa-romeo','MiTo','mito'),
  ('alfa-romeo','Crosswagon','crosswagon'),
  ('alfa-romeo','Spider','spider'),
  ('alfa-romeo','GT','gt'),
  ('alfa-romeo','Giulietta','giulietta'),
  ('alfa-romeo','Giulia','giulia'),
  ('skoda','Favorit','favorit'),
  ('skoda','Felicia','felicia'),
  ('skoda','Citigo','citigo'),
  ('skoda','Fabia','fabia'),
  ('skoda','Fabia Combi','fabia-combi'),
  ('skoda','Fabia Sedan','fabia-sedan'),
  ('skoda','Felicia Combi','felicia-combi'),
  ('skoda','Octavia','octavia'),
  ('skoda','Octavia Combi','octavia-combi'),
  ('skoda','Roomster','roomster'),
  ('skoda','Yeti','yeti'),
  ('skoda','Rapid','rapid'),
  ('skoda','Rapid Spaceback','rapid-spaceback'),
  ('skoda','Superb','superb'),
  ('skoda','Superb Combi','superb-combi'),
  ('chevrolet','Alero','alero'),
  ('chevrolet','Aveo','aveo'),
  ('chevrolet','Camaro','camaro'),
  ('chevrolet','Captiva','captiva'),
  ('chevrolet','Corvette','corvette'),
  ('chevrolet','Cruze','cruze'),
  ('chevrolet','Cruze SW','cruze-sw'),
  ('chevrolet','Epica','epica'),
  ('chevrolet','Equinox','equinox'),
  ('chevrolet','Evanda','evanda'),
  ('chevrolet','HHR','hhr'),
  ('chevrolet','Kalos','kalos'),
  ('chevrolet','Lacetti','lacetti'),
  ('chevrolet','Lacetti SW','lacetti-sw'),
  ('chevrolet','Lumina','lumina'),
  ('chevrolet','Malibu','malibu'),
  ('chevrolet','Matiz','matiz'),
  ('chevrolet','Monte Carlo','monte-carlo'),
  ('chevrolet','Nubira','nubira'),
  ('chevrolet','Orlando','orlando'),
  ('chevrolet','Spark','spark'),
  ('chevrolet','Suburban','suburban'),
  ('chevrolet','Tacuma','tacuma'),
  ('chevrolet','Tahoe','tahoe'),
  ('chevrolet','Trax','trax'),
  ('porsche','911 Carrera','911-carrera'),
  ('porsche','911 Carrera Cabrio','911-carrera-cabrio'),
  ('porsche','911 Targa','911-targa'),
  ('porsche','911 Turbo','911-turbo'),
  ('porsche','924','924'),
  ('porsche','944','944'),
  ('porsche','997','997'),
  ('porsche','Boxster','boxster'),
  ('porsche','Cayenne','cayenne'),
  ('porsche','Cayman','cayman'),
  ('porsche','Macan','macan'),
  ('porsche','Panamera','panamera'),
  ('honda','Accord','accord'),
  ('honda','Accord Coupé','accord-coupe'),
  ('honda','Accord Tourer','accord-tourer'),
  ('honda','City','city'),
  ('honda','Civic','civic'),
  ('honda','Civic Aerodeck','civic-aerodeck'),
  ('honda','Civic Coupé','civic-coupe'),
  ('honda','Civic Tourer','civic-tourer'),
  ('honda','Civic Type R','civic-type-r'),
  ('honda','CR-V','cr-v'),
  ('honda','CR-X','cr-x'),
  ('honda','CR-Z','cr-z'),
  ('honda','FR-V','fr-v'),
  ('honda','HR-V','hr-v'),
  ('honda','Insight','insight'),
  ('honda','Integra','integra'),
  ('honda','Jazz','jazz'),
  ('honda','Legend','legend'),
  ('honda','Prelude','prelude'),
  ('subaru','BRZ','brz'),
  ('subaru','Forester','forester'),
  ('subaru','Impreza','impreza'),
  ('subaru','Impreza Wagon','impreza-wagon'),
  ('subaru','Justy','justy'),
  ('subaru','Legacy','legacy'),
  ('subaru','Legacy Wagon','legacy-wagon'),
  ('subaru','Legacy Outback','legacy-outback'),
  ('subaru','Levorg','levorg'),
  ('subaru','Outback','outback'),
  ('subaru','SVX','svx'),
  ('subaru','Tribeca','tribeca'),
  ('subaru','Tribeca B9','tribeca-b9'),
  ('subaru','XV','xv'),
  ('mazda','121','121'),
  ('mazda','2','2'),
  ('mazda','3','3'),
  ('mazda','323','323'),
  ('mazda','323 Combi','323-combi'),
  ('mazda','323 Coupé','323-coupe'),
  ('mazda','323 F','323-f'),
  ('mazda','5','5'),
  ('mazda','6','6'),
  ('mazda','6 Combi','6-combi'),
  ('mazda','626','626'),
  ('mazda','626 Combi','626-combi'),
  ('mazda','B-Fighter','b-fighter'),
  ('mazda','B2500','b2500'),
  ('mazda','BT','bt'),
  ('mazda','CX-3','cx-3'),
  ('mazda','CX-5','cx-5'),
  ('mazda','CX-7','cx-7'),
  ('mazda','CX-9','cx-9'),
  ('mazda','Demio','demio'),
  ('mazda','MPV','mpv'),
  ('mazda','MX-3','mx-3'),
  ('mazda','MX-5','mx-5'),
  ('mazda','MX-6','mx-6'),
  ('mazda','Premacy','premacy'),
  ('mazda','RX-7','rx-7'),
  ('mazda','RX-8','rx-8'),
  ('mazda','Xedox 6','xedox-6'),
  ('mitsubishi','3000 GT','3000-gt'),
  ('mitsubishi','ASX','asx'),
  ('mitsubishi','Carisma','carisma'),
  ('mitsubishi','Colt','colt'),
  ('mitsubishi','Colt CC','colt-cc'),
  ('mitsubishi','Eclipse','eclipse'),
  ('mitsubishi','Fuso canter','fuso-canter'),
  ('mitsubishi','Galant','galant'),
  ('mitsubishi','Galant Combi','galant-combi'),
  ('mitsubishi','Grandis','grandis'),
  ('mitsubishi','L200','l200'),
  ('mitsubishi','L200 Pick up','l200-pick-up'),
  ('mitsubishi','L200 Pick up Allrad','l200-pick-up-allrad'),
  ('mitsubishi','L300','l300'),
  ('mitsubishi','Lancer','lancer'),
  ('mitsubishi','Lancer Combi','lancer-combi'),
  ('mitsubishi','Lancer Evo','lancer-evo'),
  ('mitsubishi','Lancer Sportback','lancer-sportback'),
  ('mitsubishi','Outlander','outlander'),
  ('mitsubishi','Pajero','pajero'),
  ('mitsubishi','Pajeto Pinin','pajeto-pinin'),
  ('mitsubishi','Pajero Pinin Wagon','pajero-pinin-wagon'),
  ('mitsubishi','Pajero Sport','pajero-sport'),
  ('mitsubishi','Pajero Wagon','pajero-wagon'),
  ('mitsubishi','Space Star','space-star'),
  ('lexus','CT','ct'),
  ('lexus','GS','gs'),
  ('lexus','GS 300','gs-300'),
  ('lexus','GX','gx'),
  ('lexus','IS','is'),
  ('lexus','IS 200','is-200'),
  ('lexus','IS 250 C','is-250-c'),
  ('lexus','IS-F','is-f'),
  ('lexus','LS','ls'),
  ('lexus','LX','lx'),
  ('lexus','NX','nx'),
  ('lexus','RC F','rc-f'),
  ('lexus','RX','rx'),
  ('lexus','RX 300','rx-300'),
  ('lexus','RX 400h','rx-400h'),
  ('lexus','RX 450h','rx-450h'),
  ('lexus','SC 430','sc-430'),
  ('toyota','4-Runner','4-runner'),
  ('toyota','Auris','auris'),
  ('toyota','Avensis','avensis'),
  ('toyota','Avensis Combi','avensis-combi'),
  ('toyota','Avensis Van Verso','avensis-van-verso'),
  ('toyota','Aygo','aygo'),
  ('toyota','Camry','camry'),
  ('toyota','Carina','carina'),
  ('toyota','Celica','celica'),
  ('toyota','Corolla','corolla'),
  ('toyota','Corolla Combi','corolla-combi'),
  ('toyota','Corolla sedan','corolla-sedan'),
  ('toyota','Corolla Verso','corolla-verso'),
  ('toyota','FJ Cruiser','fj-cruiser'),
  ('toyota','GT86','gt86'),
  ('toyota','Hiace','hiace'),
  ('toyota','Hiace Van','hiace-van'),
  ('toyota','Highlander','highlander'),
  ('toyota','Hilux','hilux'),
  ('toyota','Land Cruiser','land-cruiser'),
  ('toyota','MR2','mr2'),
  ('toyota','Paseo','paseo'),
  ('toyota','Picnic','picnic'),
  ('toyota','Prius','prius'),
  ('toyota','RAV4','rav4'),
  ('toyota','Sequoia','sequoia'),
  ('toyota','Starlet','starlet'),
  ('toyota','Supra','supra'),
  ('toyota','Tundra','tundra'),
  ('toyota','Urban Cruiser','urban-cruiser'),
  ('toyota','Verso','verso'),
  ('toyota','Yaris','yaris'),
  ('toyota','Yaris Verso','yaris-verso'),
  ('bmw','i3','i3'),
  ('bmw','i8','i8'),
  ('bmw','M3','m3'),
  ('bmw','M4','m4'),
  ('bmw','M5','m5'),
  ('bmw','M6','m6'),
  ('bmw','Rad 1','rad-1'),
  ('bmw','Rad 1 Cabrio','rad-1-cabrio'),
  ('bmw','Rad 1 Coupé','rad-1-coupe'),
  ('bmw','Rad 2','rad-2'),
  ('bmw','Rad 2 Active Tourer','rad-2-active-tourer'),
  ('bmw','Rad 2 Coupé','rad-2-coupe'),
  ('bmw','Rad 2 Gran Tourer','rad-2-gran-tourer'),
  ('bmw','Rad 3','rad-3'),
  ('bmw','Rad 3 Cabrio','rad-3-cabrio'),
  ('bmw','Rad 3 Compact','rad-3-compact'),
  ('bmw','Rad 3 Coupé','rad-3-coupe'),
  ('bmw','Rad 3 GT','rad-3-gt'),
  ('bmw','Rad 3 Touring','rad-3-touring'),
  ('bmw','Rad 4','rad-4'),
  ('bmw','Rad 4 Cabrio','rad-4-cabrio'),
  ('bmw','Rad 4 Gran Coupé','rad-4-gran-coupe'),
  ('bmw','Rad 5','rad-5'),
  ('bmw','Rad 5 GT','rad-5-gt'),
  ('bmw','Rad 5 Touring','rad-5-touring'),
  ('bmw','Rad 6','rad-6'),
  ('bmw','Rad 6 Cabrio','rad-6-cabrio'),
  ('bmw','Rad 6 Coupé','rad-6-coupe'),
  ('bmw','Rad 6 Gran Coupé','rad-6-gran-coupe'),
  ('bmw','Rad 7','rad-7'),
  ('bmw','Rad 8 Coupé','rad-8-coupe'),
  ('bmw','X1','x1'),
  ('bmw','X3','x3'),
  ('bmw','X4','x4'),
  ('bmw','X5','x5'),
  ('bmw','X6','x6'),
  ('bmw','Z3','z3'),
  ('bmw','Z3 Coupé','z3-coupe'),
  ('bmw','Z3 Roadster','z3-roadster'),
  ('bmw','Z4','z4'),
  ('bmw','Z4 Roadster','z4-roadster'),
  ('volkswagen','Amarok','amarok'),
  ('volkswagen','Beetle','beetle'),
  ('volkswagen','Bora','bora'),
  ('volkswagen','Bora Variant','bora-variant'),
  ('volkswagen','Caddy','caddy'),
  ('volkswagen','Caddy Van','caddy-van'),
  ('volkswagen','Life','life'),
  ('volkswagen','California','california'),
  ('volkswagen','Caravelle','caravelle'),
  ('volkswagen','CC','cc'),
  ('volkswagen','Crafter','crafter'),
  ('volkswagen','Crafter Van','crafter-van'),
  ('volkswagen','Crafter Kombi','crafter-kombi'),
  ('volkswagen','CrossTouran','crosstouran'),
  ('volkswagen','Eos','eos'),
  ('volkswagen','Fox','fox'),
  ('volkswagen','Golf','golf'),
  ('volkswagen','Golf Cabrio','golf-cabrio'),
  ('volkswagen','Golf Plus','golf-plus'),
  ('volkswagen','Golf Sportvan','golf-sportvan'),
  ('volkswagen','Golf Variant','golf-variant'),
  ('volkswagen','Jetta','jetta'),
  ('volkswagen','LT','lt'),
  ('volkswagen','Lupo','lupo'),
  ('volkswagen','Multivan','multivan'),
  ('volkswagen','New Beetle','new-beetle'),
  ('volkswagen','New Beetle Cabrio','new-beetle-cabrio'),
  ('volkswagen','Passat','passat'),
  ('volkswagen','Passat Alltrack','passat-alltrack'),
  ('volkswagen','Passat CC','passat-cc'),
  ('volkswagen','Passat Variant','passat-variant'),
  ('volkswagen','Passat Variant Van','passat-variant-van'),
  ('volkswagen','Phaeton','phaeton'),
  ('volkswagen','Polo','polo'),
  ('volkswagen','Polo Van','polo-van'),
  ('volkswagen','Polo Variant','polo-variant'),
  ('volkswagen','Scirocco','scirocco'),
  ('volkswagen','Sharan','sharan'),
  ('volkswagen','T4','t4'),
  ('volkswagen','T4 Caravelle','t4-caravelle'),
  ('volkswagen','T4 Multivan','t4-multivan'),
  ('volkswagen','T5','t5'),
  ('volkswagen','T5 Caravelle','t5-caravelle'),
  ('volkswagen','T5 Multivan','t5-multivan'),
  ('volkswagen','T5 Transporter Shuttle','t5-transporter-shuttle'),
  ('volkswagen','Tiguan','tiguan'),
  ('volkswagen','Touareg','touareg'),
  ('volkswagen','Touran','touran'),
  ('suzuki','Alto','alto'),
  ('suzuki','Baleno','baleno'),
  ('suzuki','Baleno kombi','baleno-kombi'),
  ('suzuki','Grand Vitara','grand-vitara'),
  ('suzuki','Grand Vitara XL-7','grand-vitara-xl-7'),
  ('suzuki','Ignis','ignis'),
  ('suzuki','Jimny','jimny'),
  ('suzuki','Kizashi','kizashi'),
  ('suzuki','Liana','liana'),
  ('suzuki','Samurai','samurai'),
  ('suzuki','Splash','splash'),
  ('suzuki','Swift','swift'),
  ('suzuki','SX4','sx4'),
  ('suzuki','SX4 Sedan','sx4-sedan'),
  ('suzuki','Vitara','vitara'),
  ('suzuki','Wagon R+','wagon-r'),
  ('mercedes-benz','100 D','100-d'),
  ('mercedes-benz','115','115'),
  ('mercedes-benz','124','124'),
  ('mercedes-benz','126','126'),
  ('mercedes-benz','190','190'),
  ('mercedes-benz','190 D','190-d'),
  ('mercedes-benz','190 E','190-e'),
  ('mercedes-benz','200 - 300','200-300'),
  ('mercedes-benz','200 D','200-d'),
  ('mercedes-benz','200 E','200-e'),
  ('mercedes-benz','210 Van','210-van'),
  ('mercedes-benz','210 kombi','210-kombi'),
  ('mercedes-benz','310 Van','310-van'),
  ('mercedes-benz','310 kombi','310-kombi'),
  ('mercedes-benz','230 - 300 CE Coupé','230-300-ce-coupe'),
  ('mercedes-benz','260 - 560 SE','260-560-se'),
  ('mercedes-benz','260 - 560 SEL','260-560-sel'),
  ('mercedes-benz','500 - 600 SEC Coupé','500-600-sec-coupe'),
  ('mercedes-benz','Trieda A','trieda-a'),
  ('mercedes-benz','A','a'),
  ('mercedes-benz','A L','a-l'),
  ('mercedes-benz','AMG GT','amg-gt'),
  ('mercedes-benz','Trieda B','trieda-b'),
  ('mercedes-benz','Trieda C','trieda-c'),
  ('mercedes-benz','C','c'),
  ('mercedes-benz','C Sportcoupé','c-sportcoupe'),
  ('mercedes-benz','C T','c-t'),
  ('mercedes-benz','Citan','citan'),
  ('mercedes-benz','CL','cl'),
  ('mercedes-benz','CLA','cla'),
  ('mercedes-benz','CLC','clc'),
  ('mercedes-benz','CLK Cabrio','clk-cabrio'),
  ('mercedes-benz','CLK Coupé','clk-coupe'),
  ('mercedes-benz','CLS','cls'),
  ('mercedes-benz','Trieda E','trieda-e'),
  ('mercedes-benz','E','e'),
  ('mercedes-benz','E Cabrio','e-cabrio'),
  ('mercedes-benz','E Coupé','e-coupe'),
  ('mercedes-benz','E T','e-t'),
  ('mercedes-benz','Trieda G','trieda-g'),
  ('mercedes-benz','G Cabrio','g-cabrio'),
  ('mercedes-benz','GL','gl'),
  ('mercedes-benz','GLA','gla'),
  ('mercedes-benz','GLC','glc'),
  ('mercedes-benz','GLE','gle'),
  ('mercedes-benz','GLK','glk'),
  ('mercedes-benz','Trieda M','trieda-m'),
  ('mercedes-benz','MB 100','mb-100'),
  ('mercedes-benz','Trieda R','trieda-r'),
  ('mercedes-benz','Trieda S','trieda-s'),
  ('mercedes-benz','S','s'),
  ('mercedes-benz','S Coupé','s-coupe'),
  ('mercedes-benz','SL','sl'),
  ('mercedes-benz','SLC','slc'),
  ('mercedes-benz','SLK','slk'),
  ('mercedes-benz','SLR','slr'),
  ('mercedes-benz','Sprinter','sprinter'),
  ('saab','9-3','9-3'),
  ('saab','9-3 Cabriolet','9-3-cabriolet'),
  ('saab','9-3 Coupé','9-3-coupe'),
  ('saab','9-3 SportCombi','9-3-sportcombi'),
  ('saab','9-5','9-5'),
  ('saab','9-5 SportCombi','9-5-sportcombi'),
  ('saab','900','900'),
  ('saab','900 C','900-c'),
  ('saab','900 C Turbo','900-c-turbo'),
  ('saab','9000','9000'),
  ('audi','100','100'),
  ('audi','100 Avant','100-avant'),
  ('audi','80','80'),
  ('audi','80 Avant','80-avant'),
  ('audi','80 Cabrio','80-cabrio'),
  ('audi','90','90'),
  ('audi','A1','a1'),
  ('audi','A2','a2'),
  ('audi','A3','a3'),
  ('audi','A3 Cabriolet','a3-cabriolet'),
  ('audi','A3 Limuzina','a3-limuzina'),
  ('audi','A3 Sportback','a3-sportback'),
  ('audi','A4','a4'),
  ('audi','A4 Allroad','a4-allroad'),
  ('audi','A4 Avant','a4-avant'),
  ('audi','A4 Cabriolet','a4-cabriolet'),
  ('audi','A5','a5'),
  ('audi','A5 Cabriolet','a5-cabriolet'),
  ('audi','A5 Sportback','a5-sportback'),
  ('audi','A6','a6'),
  ('audi','A6 Allroad','a6-allroad'),
  ('audi','A6 Avant','a6-avant'),
  ('audi','A7','a7'),
  ('audi','A8','a8'),
  ('audi','A8 Long','a8-long'),
  ('audi','Q3','q3'),
  ('audi','Q5','q5'),
  ('audi','Q7','q7'),
  ('audi','R8','r8'),
  ('audi','RS4 Cabriolet','rs4-cabriolet'),
  ('audi','RS4/RS4 Avant','rs4-rs4-avant'),
  ('audi','RS5','rs5'),
  ('audi','RS6 Avant','rs6-avant'),
  ('audi','RS7','rs7'),
  ('audi','S3/S3 Sportback','s3-s3-sportback'),
  ('audi','S4 Cabriolet','s4-cabriolet'),
  ('audi','S4/S4 Avant','s4-s4-avant'),
  ('audi','S5/S5 Cabriolet','s5-s5-cabriolet'),
  ('audi','S6/RS6','s6-rs6'),
  ('audi','S7','s7'),
  ('audi','S8','s8'),
  ('audi','SQ5','sq5'),
  ('audi','TT Coupé','tt-coupe'),
  ('audi','TT Roadster','tt-roadster'),
  ('audi','TTS','tts'),
  ('kia','Avella','avella'),
  ('kia','Besta','besta'),
  ('kia','Carens','carens'),
  ('kia','Carnival','carnival'),
  ('kia','Cee`d','cee-d'),
  ('kia','Cee`d SW','cee-d-sw'),
  ('kia','Cerato','cerato'),
  ('kia','K 2500','k-2500'),
  ('kia','Magentis','magentis'),
  ('kia','Opirus','opirus'),
  ('kia','Optima','optima'),
  ('kia','Picanto','picanto'),
  ('kia','Pregio','pregio'),
  ('kia','Pride','pride'),
  ('kia','Pro Cee`d','pro-cee-d'),
  ('kia','Rio','rio'),
  ('kia','Rio Combi','rio-combi'),
  ('kia','Rio sedan','rio-sedan'),
  ('kia','Sephia','sephia'),
  ('kia','Shuma','shuma'),
  ('kia','Sorento','sorento'),
  ('kia','Soul','soul'),
  ('kia','Sportage','sportage'),
  ('kia','Venga','venga'),
  ('land-rover','109','109'),
  ('land-rover','Defender','defender'),
  ('land-rover','Discovery','discovery'),
  ('land-rover','Discovery Sport','discovery-sport'),
  ('land-rover','Freelander','freelander'),
  ('land-rover','Range Rover','range-rover'),
  ('land-rover','Range Rover Evoque','range-rover-evoque'),
  ('land-rover','Range Rover Sport','range-rover-sport'),
  ('dodge','Avenger','avenger'),
  ('dodge','Caliber','caliber'),
  ('dodge','Challenger','challenger'),
  ('dodge','Charger','charger'),
  ('dodge','Grand Caravan','grand-caravan'),
  ('dodge','Journey','journey'),
  ('dodge','Magnum','magnum'),
  ('dodge','Nitro','nitro'),
  ('dodge','RAM','ram'),
  ('dodge','Stealth','stealth'),
  ('dodge','Viper','viper'),
  ('chrysler','300 C','300-c'),
  ('chrysler','300 C Touring','300-c-touring'),
  ('chrysler','300 M','300-m'),
  ('chrysler','Crossfire','crossfire'),
  ('chrysler','Grand Voyager','grand-voyager'),
  ('chrysler','LHS','lhs'),
  ('chrysler','Neon','neon'),
  ('chrysler','Pacifica','pacifica'),
  ('chrysler','Plymouth','plymouth'),
  ('chrysler','PT Cruiser','pt-cruiser'),
  ('chrysler','Sebring','sebring'),
  ('chrysler','Sebring Convertible','sebring-convertible'),
  ('chrysler','Stratus','stratus'),
  ('chrysler','Stratus Cabrio','stratus-cabrio'),
  ('chrysler','Town & Country','town-country'),
  ('chrysler','Voyager','voyager'),
  ('ford','Aerostar','aerostar'),
  ('ford','B-Max','b-max'),
  ('ford','C-Max','c-max'),
  ('ford','Cortina','cortina'),
  ('ford','Cougar','cougar'),
  ('ford','Edge','edge'),
  ('ford','Escort','escort'),
  ('ford','Escort Cabrio','escort-cabrio'),
  ('ford','Escort kombi','escort-kombi'),
  ('ford','Explorer','explorer'),
  ('ford','F-150','f-150'),
  ('ford','F-250','f-250'),
  ('ford','Fiesta','fiesta'),
  ('ford','Focus','focus'),
  ('ford','Focus C-Max','focus-c-max'),
  ('ford','Focus CC','focus-cc'),
  ('ford','Focus kombi','focus-kombi'),
  ('ford','Fusion','fusion'),
  ('ford','Galaxy','galaxy'),
  ('ford','Grand C-Max','grand-c-max'),
  ('ford','Ka','ka'),
  ('ford','Kuga','kuga'),
  ('ford','Maverick','maverick'),
  ('ford','Mondeo','mondeo'),
  ('ford','Mondeo Combi','mondeo-combi'),
  ('ford','Mustang','mustang'),
  ('ford','Orion','orion'),
  ('ford','Puma','puma'),
  ('ford','Ranger','ranger'),
  ('ford','S-Max','s-max'),
  ('ford','Sierra','sierra'),
  ('ford','Street Ka','street-ka'),
  ('ford','Tourneo Connect','tourneo-connect'),
  ('ford','Tourneo Custom','tourneo-custom'),
  ('ford','Transit','transit'),
  ('ford','Transit Bus','transit-bus'),
  ('ford','Transit Connect LWB','transit-connect-lwb'),
  ('ford','Transit Courier','transit-courier'),
  ('ford','Transit Custom','transit-custom'),
  ('ford','Transit kombi','transit-kombi'),
  ('ford','Transit Tourneo','transit-tourneo'),
  ('ford','Transit Valnik','transit-valnik'),
  ('ford','Transit Van','transit-van'),
  ('ford','Transit Van 350','transit-van-350'),
  ('ford','Windstar','windstar'),
  ('hummer','H2','h2'),
  ('hummer','H3','h3'),
  ('hyundai','Accent','accent'),
  ('hyundai','Atos','atos'),
  ('hyundai','Atos Prime','atos-prime'),
  ('hyundai','Coupé','coupe'),
  ('hyundai','Elantra','elantra'),
  ('hyundai','Galloper','galloper'),
  ('hyundai','Genesis','genesis'),
  ('hyundai','Getz','getz'),
  ('hyundai','Grandeur','grandeur'),
  ('hyundai','H 350','h-350'),
  ('hyundai','H1','h1'),
  ('hyundai','H1 Bus','h1-bus'),
  ('hyundai','H1 Van','h1-van'),
  ('hyundai','H200','h200'),
  ('hyundai','i10','i10'),
  ('hyundai','i20','i20'),
  ('hyundai','i30','i30'),
  ('hyundai','i30 CW','i30-cw'),
  ('hyundai','i40','i40'),
  ('hyundai','i40 CW','i40-cw'),
  ('hyundai','ix20','ix20'),
  ('hyundai','ix35','ix35'),
  ('hyundai','ix55','ix55'),
  ('hyundai','Lantra','lantra'),
  ('hyundai','Matrix','matrix'),
  ('hyundai','Santa Fe','santa-fe'),
  ('hyundai','Sonata','sonata'),
  ('hyundai','Terracan','terracan'),
  ('hyundai','Trajet','trajet'),
  ('hyundai','Tucson','tucson'),
  ('hyundai','Veloster','veloster'),
  ('infiniti','EX','ex'),
  ('infiniti','FX','fx'),
  ('infiniti','G','g'),
  ('infiniti','G Coupé','g-coupe'),
  ('infiniti','M','m'),
  ('infiniti','Q','q'),
  ('infiniti','QX','qx'),
  ('jaguar','Daimler','daimler'),
  ('jaguar','F-Pace','f-pace'),
  ('jaguar','F-Type','f-type'),
  ('jaguar','S-Type','s-type'),
  ('jaguar','Sovereign','sovereign'),
  ('jaguar','X-Type','x-type'),
  ('jaguar','X-type Estate','x-type-estate'),
  ('jaguar','XE','xe'),
  ('jaguar','XF','xf'),
  ('jaguar','XJ','xj'),
  ('jaguar','XJ12','xj12'),
  ('jaguar','XJ6','xj6'),
  ('jaguar','XJ8','xj8'),
  ('jaguar','XJR','xjr'),
  ('jaguar','XK','xk'),
  ('jaguar','XK8 Convertible','xk8-convertible'),
  ('jaguar','XKR','xkr'),
  ('jaguar','XKR Convertible','xkr-convertible'),
  ('jeep','Cherokee','cherokee'),
  ('jeep','Commander','commander'),
  ('jeep','Compass','compass'),
  ('jeep','Grand Cherokee','grand-cherokee'),
  ('jeep','Patriot','patriot'),
  ('jeep','Renegade','renegade'),
  ('jeep','Wrangler','wrangler'),
  ('nissan','100 NX','100-nx'),
  ('nissan','200 SX','200-sx'),
  ('nissan','350 Z','350-z'),
  ('nissan','350 Z Roadster','350-z-roadster'),
  ('nissan','370 Z','370-z'),
  ('nissan','Almera','almera'),
  ('nissan','Almera Tino','almera-tino'),
  ('nissan','Cabstar E - T','cabstar-e-t'),
  ('nissan','Cabstar TL2 Valnik','cabstar-tl2-valnik'),
  ('nissan','e-NV200','e-nv200'),
  ('nissan','GT-R','gt-r'),
  ('nissan','Insterstar','insterstar'),
  ('nissan','Juke','juke'),
  ('nissan','King Cab','king-cab'),
  ('nissan','Leaf','leaf'),
  ('nissan','Maxima','maxima'),
  ('nissan','Maxima QX','maxima-qx'),
  ('nissan','Micra','micra'),
  ('nissan','Murano','murano'),
  ('nissan','Navara','navara'),
  ('nissan','Note','note'),
  ('nissan','NP300 Pickup','np300-pickup'),
  ('nissan','NV200','nv200'),
  ('nissan','NV400','nv400'),
  ('nissan','Pathfinder','pathfinder'),
  ('nissan','Patrol','patrol'),
  ('nissan','Patrol GR','patrol-gr'),
  ('nissan','Pickup','pickup'),
  ('nissan','Pixo','pixo'),
  ('nissan','Primastar','primastar'),
  ('nissan','Primastar Combi','primastar-combi'),
  ('nissan','Primera','primera'),
  ('nissan','Primera Combi','primera-combi'),
  ('nissan','Pulsar','pulsar'),
  ('nissan','Qashqai','qashqai'),
  ('nissan','Serena','serena'),
  ('nissan','Sunny','sunny'),
  ('nissan','Terrano','terrano'),
  ('nissan','Tiida','tiida'),
  ('nissan','Trade','trade'),
  ('nissan','Vanette Cargo','vanette-cargo'),
  ('nissan','X-Trail','x-trail'),
  ('volvo','240','240'),
  ('volvo','340','340'),
  ('volvo','360','360'),
  ('volvo','460','460'),
  ('volvo','850','850'),
  ('volvo','850 kombi','850-kombi'),
  ('volvo','C30','c30'),
  ('volvo','C70','c70'),
  ('volvo','C70 Cabrio','c70-cabrio'),
  ('volvo','C70 Coupé','c70-coupe'),
  ('volvo','S40','s40'),
  ('volvo','S60','s60'),
  ('volvo','S70','s70'),
  ('volvo','S80','s80'),
  ('volvo','S90','s90'),
  ('volvo','V40','v40'),
  ('volvo','V50','v50'),
  ('volvo','V60','v60'),
  ('volvo','V70','v70'),
  ('volvo','V90','v90'),
  ('volvo','XC60','xc60'),
  ('volvo','XC70','xc70'),
  ('volvo','XC90','xc90'),
  ('daewoo','Espero','espero'),
  ('daewoo','Kalos','kalos'),
  ('daewoo','Lacetti','lacetti'),
  ('daewoo','Lanos','lanos'),
  ('daewoo','Leganza','leganza'),
  ('daewoo','Lublin','lublin'),
  ('daewoo','Matiz','matiz'),
  ('daewoo','Nexia','nexia'),
  ('daewoo','Nubira','nubira'),
  ('daewoo','Nubira kombi','nubira-kombi'),
  ('daewoo','Racer','racer'),
  ('daewoo','Tacuma','tacuma'),
  ('daewoo','Tico','tico'),
  ('fiat','1100','1100'),
  ('fiat','126','126'),
  ('fiat','500','500'),
  ('fiat','500L','500l'),
  ('fiat','500X','500x'),
  ('fiat','850','850'),
  ('fiat','Barchetta','barchetta'),
  ('fiat','Brava','brava'),
  ('fiat','Cinquecento','cinquecento'),
  ('fiat','Coupé','coupe'),
  ('fiat','Croma','croma'),
  ('fiat','Doblo','doblo'),
  ('fiat','Doblo Cargo','doblo-cargo'),
  ('fiat','Doblo Cargo Combi','doblo-cargo-combi'),
  ('fiat','Ducato','ducato'),
  ('fiat','Ducato Van','ducato-van'),
  ('fiat','Ducato Kombi','ducato-kombi'),
  ('fiat','Ducato Podvozok','ducato-podvozok'),
  ('fiat','Florino','florino'),
  ('fiat','Florino Combi','florino-combi'),
  ('fiat','Freemont','freemont'),
  ('fiat','Grande Punto','grande-punto'),
  ('fiat','Idea','idea'),
  ('fiat','Linea','linea'),
  ('fiat','Marea','marea'),
  ('fiat','Marea Weekend','marea-weekend'),
  ('fiat','Multipla','multipla'),
  ('fiat','Palio Weekend','palio-weekend'),
  ('fiat','Panda','panda'),
  ('fiat','Panda Van','panda-van'),
  ('fiat','Punto','punto'),
  ('fiat','Punto Cabriolet','punto-cabriolet'),
  ('fiat','Punto Evo','punto-evo'),
  ('fiat','Punto Van','punto-van'),
  ('fiat','Qubo','qubo'),
  ('fiat','Scudo','scudo'),
  ('fiat','Scudo Van','scudo-van'),
  ('fiat','Scudo Kombi','scudo-kombi'),
  ('fiat','Sedici','sedici'),
  ('fiat','Seicento','seicento'),
  ('fiat','Stilo','stilo'),
  ('fiat','Stilo Multiwagon','stilo-multiwagon'),
  ('fiat','Strada','strada'),
  ('fiat','Talento','talento'),
  ('fiat','Tipo','tipo'),
  ('fiat','Ulysse','ulysse'),
  ('fiat','Uno','uno'),
  ('fiat','X1/9','x1-9'),
  ('mini','Cooper','cooper'),
  ('mini','Cooper Cabrio','cooper-cabrio'),
  ('mini','Cooper Clubman','cooper-clubman'),
  ('mini','Cooper D','cooper-d'),
  ('mini','Cooper D Clubman','cooper-d-clubman'),
  ('mini','Cooper S','cooper-s'),
  ('mini','Cooper S Cabrio','cooper-s-cabrio'),
  ('mini','Cooper S Clubman','cooper-s-clubman'),
  ('mini','Countryman','countryman'),
  ('mini','Mini One','mini-one'),
  ('mini','One D','one-d'),
  ('rover','200','200'),
  ('rover','214','214'),
  ('rover','218','218'),
  ('rover','25','25'),
  ('rover','400','400'),
  ('rover','414','414'),
  ('rover','416','416'),
  ('rover','620','620'),
  ('rover','75','75'),
  ('smart','Cabrio','cabrio'),
  ('smart','City-Coupé','city-coupe'),
  ('smart','Compact Pulse','compact-pulse'),
  ('smart','Forfour','forfour'),
  ('smart','Fortwo cabrio','fortwo-cabrio'),
  ('smart','Fortwo coupé','fortwo-coupe'),
  ('smart','Roadster','roadster')
) as x(marka_slug, ad, slug) on m.slug = x.marka_slug
on conflict (marka_id, ad) do nothing;

-- Donanim ozellikleri (kategorili)
insert into donanim_ozellikleri (kategori, ad, slug) values
  ('Güvenlik','ABS','abs'),
  ('Güvenlik','ESP / VSA','esp'),
  ('Güvenlik','Hava Yastığı (Sürücü)','hava-yastigi-surucu'),
  ('Güvenlik','Hava Yastığı (Yan)','hava-yastigi-yan'),
  ('Güvenlik','Geri Görüş Kamerası','geri-gorus-kamerasi'),
  ('Güvenlik','Park Sensörü','park-sensoru'),
  ('Güvenlik','Lastik Basınç Sensörü','lastik-basinc'),
  ('Konfor','Hız Sabitleyici','hiz-sabitleyici'),
  ('Konfor','Klima (Dijital)','klima-dijital'),
  ('Konfor','Deri Döşeme','deri-doseme'),
  ('Konfor','Isıtmalı Koltuk','isitmali-koltuk'),
  ('Konfor','Sunroof','sunroof'),
  ('Konfor','Start/Stop','start-stop'),
  ('Konfor','Anahtarsız Giriş','anahtarsiz-giris'),
  ('Multimedya','Dokunmatik Ekran','dokunmatik-ekran'),
  ('Multimedya','Apple CarPlay','apple-carplay'),
  ('Multimedya','Android Auto','android-auto'),
  ('Multimedya','Bluetooth','bluetooth'),
  ('Multimedya','Navigasyon','navigasyon'),
  ('Dış Donanım','LED Far','led-far'),
  ('Dış Donanım','Sis Farı','sis-fari'),
  ('Dış Donanım','Alaşım Jant','alasim-jant'),
  ('Dış Donanım','Far Yıkama','far-yikama')
on conflict (slug) do nothing;
